<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\ChoiceProvider\DispatchPointChoiceProvider' shared autowired service.

return $this->privates['InPost\\Shipping\\ChoiceProvider\\DispatchPointChoiceProvider'] = new \InPost\Shipping\ChoiceProvider\DispatchPointChoiceProvider(($this->services['inpost.shipping.presenter.dispatch_point'] ?? ($this->services['inpost.shipping.presenter.dispatch_point'] = new \InPost\Shipping\Presenter\DispatchPointPresenter())));
