<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.configuration.szybkie_zwroty' shared service.

return $this->services['inpost.shipping.configuration.szybkie_zwroty'] = new \InPost\Shipping\Configuration\SzybkieZwrotyConfiguration();
