<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.choice_provider.product_template' shared autowired service.

return $this->services['inpost.shipping.choice_provider.product_template'] = new \InPost\Shipping\ChoiceProvider\ProductTemplateChoiceProvider(($this->services['inpost.shipping.translations.dimension_template'] ?? $this->load('getInpost_Shipping_Translations_DimensionTemplateService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\ShippingServiceChoiceProvider'] ?? $this->load('getShippingServiceChoiceProviderService.php')));
