<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.dispatch_order.update' shared autowired service.

return $this->services['inpost.shipping.handler.dispatch_order.update'] = new \InPost\Shipping\Handler\DispatchOrder\UpdateDispatchOrderHandler(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())));
