<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.shipment.update_status' shared service.

return $this->services['inpost.shipping.handler.shipment.update_status'] = new \InPost\Shipping\Handler\Shipment\UpdateShipmentStatusHandler(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())), ($this->services['inpost.shipping.configuration.orders'] ?? ($this->services['inpost.shipping.configuration.orders'] = new \InPost\Shipping\Configuration\OrdersConfiguration())), new \InPost\Shipping\Repository\ObjectModel\ShipmentRepository(\Db::getInstance()));
