<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmOzx8Y\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmOzx8Y/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXmOzx8Y.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXmOzx8Y\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXmOzx8Y\appAppKernelProdContainer([
    'container.build_hash' => 'XmOzx8Y',
    'container.build_id' => 'ed74b1b9',
    'container.build_time' => 1728896392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmOzx8Y');
