<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHGCkgAX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHGCkgAX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHGCkgAX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHGCkgAX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHGCkgAX\appAppKernelProdContainer([
    'container.build_hash' => 'HGCkgAX',
    'container.build_id' => '6fffbf4c',
    'container.build_time' => 1732260547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHGCkgAX');
