<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfN8rcJ\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfN8rcJ/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRfN8rcJ.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRfN8rcJ\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerRfN8rcJ\appAppKernelDevDebugContainer([
    'container.build_hash' => 'RfN8rcJ',
    'container.build_id' => 'bc4a4134',
    'container.build_time' => 1728475404,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfN8rcJ');
