services:
    _defaults:
        public: true

    ##############
    # Your Module

    smartargetsocialfollowbar.module:
        class: smartargetsocialfollowbar
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'smartargetsocialfollowbar'

    smartargetsocialfollowbar.context:
        class: Context
        factory: ['Context', 'getContext']

    #####################
    # PrestaShop Account
    smartargetsocialfollowbar.ps_accounts_installer:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
        arguments:
            - '5.0'

    smartargetsocialfollowbar.ps_accounts_facade:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
        arguments:
            - '@smartargetsocialfollowbar.ps_accounts_installer'

    #####################
    # PrestaShop Billing

    smartargetsocialfollowbar.ps_billings_context_wrapper:
        class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
        arguments:
            - '@smartargetsocialfollowbar.ps_accounts_facade'
            - '@smartargetsocialfollowbar.context'
            - false # if true, enables the sandbox mode, if false or empty, disables it

    smartargetsocialfollowbar.ps_billings_facade:
        class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
        public: true
        arguments:
            - '@smartargetsocialfollowbar.ps_billings_context_wrapper'
            - '@smartargetsocialfollowbar.module'

    # Remove this if you do not need BillingService
    smartargetsocialfollowbar.ps_billings_service:
        class: 'PrestaShopCorp\Billing\Services\BillingService'
        public: true
        arguments:
            - '@smartargetsocialfollowbar.ps_billings_context_wrapper'
            - '@smartargetsocialfollowbar.module'
