{*
* 2017 Areama
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Areama <contact@areama.net>
*  @copyright  2017 Areama
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Areama
*}

<div class="arlg-config-panel {if $active_tab != 'ArLgSliderConfigForm' && $active_tab != 'ArLgSliderMobileConfigForm'}hidden{/if}" id="arlg-slider">
    <div class="panel">
        <div class="panel-heading">
            <i class="icon-info"></i> {l s='Slider settings' mod='arlg'}
        </div>
        <div class="form-wrapper">
            <ul class="nav nav-tabs">
                <li class="{if $active_tab != 'ArLgSliderMobileConfigForm'}active{/if}">
                    <a href="#arlg-slider-desktop" id="arcu-prompt-desktop-tab" data-toggle="tab">{l s='Desktop' mod='arlg'}</a>
                </li>
                <li class="{if $active_tab == 'ArLgSliderMobileConfigForm'}active{/if}">
                    <a href="#arlg-slider-mobile" id="arcu-prompt-desktop-tab" data-toggle="tab">{l s='Mobile' mod='arlg'}</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane {if $active_tab != 'ArLgSliderMobileConfigForm'}active{/if}" id="arlg-slider-desktop">
                    {$form->generateForm($sliderFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
                <div class="tab-pane {if $active_tab == 'ArLgSliderMobileConfigForm'}active{/if}" id="arlg-slider-mobile">
                    {$form->generateForm($sliderMobileFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
            </div>
        </div>
    </div>
</div>