<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\Builder\Shipment\CreateShipmentPayloadBuilder' shared autowired service.

$a = ($this->services['inpost.shipping.configuration.carriers'] ?? ($this->services['inpost.shipping.configuration.carriers'] = new \InPost\Shipping\Configuration\CarriersConfiguration()));
$b = ($this->privates['InPost\\Shipping\\DataProvider\\CarrierDataProvider'] ?? ($this->privates['InPost\\Shipping\\DataProvider\\CarrierDataProvider'] = new \InPost\Shipping\DataProvider\CarrierDataProvider()));

return $this->privates['InPost\\Shipping\\Builder\\Shipment\\CreateShipmentPayloadBuilder'] = new \InPost\Shipping\Builder\Shipment\CreateShipmentPayloadBuilder(($this->services['inpost.shipping.configuration.sending'] ?? ($this->services['inpost.shipping.configuration.sending'] = new \InPost\Shipping\Configuration\SendingConfiguration())), ($this->services['inpost.shipping.data_provider.customer_choice'] ?? ($this->services['inpost.shipping.data_provider.customer_choice'] = new \InPost\Shipping\DataProvider\CustomerChoiceDataProvider())), $a, $b, ($this->privates['InPost\\Shipping\\Helper\\DefaultShipmentReferenceExtractor'] ?? $this->load('getDefaultShipmentReferenceExtractorService.php')), new \InPost\Shipping\Builder\Shipment\ParcelPayloadBuilder($a, $b, ($this->privates['InPost\\Shipping\\DataProvider\\OrderDimensionsDataProvider'] ?? ($this->privates['InPost\\Shipping\\DataProvider\\OrderDimensionsDataProvider'] = new \InPost\Shipping\DataProvider\OrderDimensionsDataProvider())), ($this->privates['InPost\\Shipping\\Helper\\ParcelDimensionsComparator'] ?? $this->load('getParcelDimensionsComparatorService.php'))));
