<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.views.modal.shipment_details' shared autowired service.

return $this->services['inpost.shipping.views.modal.shipment_details'] = new \InPost\Shipping\Views\Modal\ShipmentDetailsModal(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), ($this->services['InPost\\Shipping\\Presenter\\ShipmentPresenter'] ?? $this->load('getShipmentPresenterService.php')));
