<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.install.carriers' shared autowired service.

return $this->services['inpost.shipping.install.carriers'] = new \InPost\Shipping\Install\Carriers(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
