<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.validator.orders_configuration' shared autowired service.

return $this->services['inpost.shipping.validator.orders_configuration'] = new \InPost\Shipping\Validator\OrdersConfigurationValidator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.translations.validation_errors'] ?? $this->load('getInpost_Shipping_Translations_ValidationErrorsService.php')));
