<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.store.module.organization' shared autowired service.

return $this->services['inpost.shipping.store.module.organization'] = new \InPost\Shipping\Presenter\Store\Modules\OrganizationModule(($this->privates['InPost\\Shipping\\DataProvider\\OrganizationDataProvider'] ?? $this->load('getOrganizationDataProviderService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\SendingMethodChoiceProvider'] ?? $this->load('getSendingMethodChoiceProviderService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\DispatchPointChoiceProvider'] ?? $this->load('getDispatchPointChoiceProviderService.php')));
