<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.validator.weekend_delivery_configuration' shared autowired service.

return $this->services['inpost.shipping.validator.weekend_delivery_configuration'] = new \InPost\Shipping\Validator\WeekendDeliveryConfigurationValidator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
