<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.views.modal.print_label' shared autowired service.

return $this->services['inpost.shipping.views.modal.print_label'] = new \InPost\Shipping\Views\Modal\PrintShipmentLabelModal(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), new \InPost\Shipping\ChoiceProvider\ShipmentLabelFormatChoiceProvider(), new \InPost\Shipping\ChoiceProvider\ShipmentLabelTypeChoiceProvider());
