<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.configuration.geo_widget' shared service.

return $this->services['inpost.shipping.configuration.geo_widget'] = new \InPost\Shipping\Configuration\GeoWidgetConfiguration();
