<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLUhS9xn\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLUhS9xn/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLUhS9xn.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLUhS9xn\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLUhS9xn\appAppKernelProdContainer([
    'container.build_hash' => 'LUhS9xn',
    'container.build_id' => '49f2cc73',
    'container.build_time' => 1723119120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLUhS9xn');
