<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'TrustedshopsAddon\Service\ChannelService' shared service.

return $this->services['TrustedshopsAddon\\Service\\ChannelService'] = new \TrustedshopsAddon\Service\ChannelService(($this->services['TrustedshopsAddon\\Repository\\ChannelRepository'] ?? ($this->services['TrustedshopsAddon\\Repository\\ChannelRepository'] = new \TrustedshopsAddon\Repository\ChannelRepository())), ($this->services['TrustedshopsAddon\\Service\\CredentialsService'] ?? ($this->services['TrustedshopsAddon\\Service\\CredentialsService'] = new \TrustedshopsAddon\Service\CredentialsService())), ($this->services['TrustedshopsAddon\\Service\\OrderProductService'] ?? $this->load('getOrderProductServiceService.php')));
