<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.shipment.create' shared autowired service.

return $this->services['inpost.shipping.handler.shipment.create'] = new \InPost\Shipping\Handler\Shipment\CreateShipmentHandler(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.translations.validation_errors'] ?? $this->load('getInpost_Shipping_Translations_ValidationErrorsService.php')), ($this->privates['InPost\\Shipping\\Builder\\Shipment\\CreateShipmentPayloadBuilder'] ?? $this->load('getCreateShipmentPayloadBuilderService.php')), ($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())));
