<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\ChoiceProvider\DimensionTemplateChoiceProvider' shared autowired service.

return $this->privates['InPost\\Shipping\\ChoiceProvider\\DimensionTemplateChoiceProvider'] = new \InPost\Shipping\ChoiceProvider\DimensionTemplateChoiceProvider(($this->services['inpost.shipping.translations.dimension_template'] ?? $this->load('getInpost_Shipping_Translations_DimensionTemplateService.php')));
