<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.shipx.factory.organization_request' shared service.

return $this->services['inpost.shipping.shipx.factory.organization_request'] = new \InPost\Shipping\ShipX\RequestFactory\OrganizationRequestFactory(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())), ($this->privates['InPost\\Shipping\\ShipX\\ShipXClient'] ?? $this->load('getShipXClientService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')));
