<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.data_provider.point' shared service.

return $this->services['inpost.shipping.data_provider.point'] = new \InPost\Shipping\DataProvider\PointDataProvider(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())), ($this->services['inpost.shipping.geo_widget.token_provider'] ?? $this->load('getInpost_Shipping_GeoWidget_TokenProviderService.php')), new \InPost\Shipping\Repository\PointRepository(), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')));
