<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.shop_context' shared service.

return $this->services['inpost.shipping.shop_context'] = new \InPost\Shipping\PrestaShopContext();
