<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.install.hooks' shared autowired service.

return $this->services['inpost.shipping.install.hooks'] = new \InPost\Shipping\Install\Hooks(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->services['inpost.shipping.hook_dispatcher'] ?? $this->load('getInpost_Shipping_HookDispatcherService.php')));
