<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'TrustedshopsAddon\Service\OrderStatusService' shared service.

return $this->services['TrustedshopsAddon\\Service\\OrderStatusService'] = new \TrustedshopsAddon\Service\OrderStatusService(($this->services['TrustedshopsAddon\\Service\\ChannelService'] ?? $this->load('getChannelServiceService.php')), ($this->services['TrustedshopsAddon\\Service\\CredentialsService'] ?? ($this->services['TrustedshopsAddon\\Service\\CredentialsService'] = new \TrustedshopsAddon\Service\CredentialsService())));
