<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\ChoiceProvider\ShippingServiceChoiceProvider' shared autowired service.

return $this->privates['InPost\\Shipping\\ChoiceProvider\\ShippingServiceChoiceProvider'] = new \InPost\Shipping\ChoiceProvider\ShippingServiceChoiceProvider(($this->privates['InPost\\Shipping\\DataProvider\\OrganizationDataProvider'] ?? $this->load('getOrganizationDataProviderService.php')), ($this->services['inpost.shipping.translations.shipping_service'] ?? $this->load('getInpost_Shipping_Translations_ShippingServiceService.php')));
