<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8VrpX8\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8VrpX8/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM8VrpX8.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM8VrpX8\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerM8VrpX8\appAppKernelDevDebugContainer([
    'container.build_hash' => 'M8VrpX8',
    'container.build_id' => '4f65b225',
    'container.build_time' => 1723117870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8VrpX8');
