<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.presenter.point' shared service.

return $this->services['inpost.shipping.presenter.point'] = new \InPost\Shipping\Presenter\PointPresenter(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.data_provider.language'] ?? ($this->privates['inpost.shipping.data_provider.language'] = new \InPost\Shipping\DataProvider\LanguageDataProvider())));
