<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\DataProvider\OrganizationDataProvider' shared autowired service.

return $this->privates['InPost\\Shipping\\DataProvider\\OrganizationDataProvider'] = new \InPost\Shipping\DataProvider\OrganizationDataProvider(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())));
