<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'smartargetsocialfollowbar.ps_billings_context_wrapper' shared service.

return $this->services['smartargetsocialfollowbar.ps_billings_context_wrapper'] = new \PrestaShopCorp\Billing\Wrappers\BillingContextWrapper(($this->services['smartargetsocialfollowbar.ps_accounts_facade'] ?? $this->load('getSmartargetsocialfollowbar_PsAccountsFacadeService.php')), ($this->services['smartargetsocialfollowbar.context'] ?? $this->load('getSmartargetsocialfollowbar_ContextService.php')), false);
