<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\Helper\DefaultShipmentReferenceExtractor' shared autowired service.

return $this->privates['InPost\\Shipping\\Helper\\DefaultShipmentReferenceExtractor'] = new \InPost\Shipping\Helper\DefaultShipmentReferenceExtractor(($this->services['inpost.shipping.configuration.sending'] ?? ($this->services['inpost.shipping.configuration.sending'] = new \InPost\Shipping\Configuration\SendingConfiguration())));
