<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'TrustedshopsAddon\Service\HookService' shared service.

return $this->services['TrustedshopsAddon\\Service\\HookService'] = new \TrustedshopsAddon\Service\HookService(($this->services['TrustedshopsAddon\\Service\\ChannelService'] ?? $this->load('getChannelServiceService.php')), ($this->services['TrustedshopsAddon\\Service\\OrderProductService'] ?? $this->load('getOrderProductServiceService.php')));
