<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\Helper\ParcelDimensionsComparator' shared autowired service.

return $this->privates['InPost\\Shipping\\Helper\\ParcelDimensionsComparator'] = new \InPost\Shipping\Helper\ParcelDimensionsComparator(new \InPost\Shipping\DataProvider\TemplateDimensionsDataProvider());
