<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'smartargetsocialfollowbar.ps_billings_facade' shared service.

return $this->services['smartargetsocialfollowbar.ps_billings_facade'] = new \PrestaShopCorp\Billing\Presenter\BillingPresenter(($this->services['smartargetsocialfollowbar.ps_billings_context_wrapper'] ?? $this->load('getSmartargetsocialfollowbar_PsBillingsContextWrapperService.php')), ($this->services['smartargetsocialfollowbar.module'] ?? $this->load('getSmartargetsocialfollowbar_ModuleService.php')));
