<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\Translations\Translations' shared autowired service.

return $this->privates['InPost\\Shipping\\Translations\\Translations'] = new \InPost\Shipping\Translations\Translations(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
