<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.hook_updater' shared autowired service.

return $this->services['inpost.shipping.hook_updater'] = new \InPost\Shipping\HookUpdater(($this->services['inpost.shipping.configuration.shop'] ?? ($this->services['inpost.shipping.configuration.shop'] = new \InPost\Shipping\Configuration\ShopConfiguration())), ($this->services['inpost.shipping.install.hooks'] ?? $this->load('getInpost_Shipping_Install_HooksService.php')));
