<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'inpost.shipping.module' shared service.

return $this->privates['inpost.shipping.module'] = \Module::getInstanceByName('inpostshipping');
