<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.data_provider.customer_choice' shared service.

return $this->services['inpost.shipping.data_provider.customer_choice'] = new \InPost\Shipping\DataProvider\CustomerChoiceDataProvider();
