<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvNDvT326V6umV+dy5Nx/'."\n".'BFDGvyUYS+nGEhKvaLKFVRvsGhHhPCiwV8Hq+zmnvaa1KPEEO1sY3zdlalQ7g6VY'."\n".'/j0OMSvu8gHUH0dHDg0ivVdY8FRjg01OvGozYcrqsg5dFk2P4664pKwR2b8E3MGP'."\n".'rGATGZ9LdN1ZiOGblnM8bHimpRk1bKrSu9KwzqdiojLrvt9d7fG0dEu8RUO1G/Un'."\n".'Q3OVzRADll2AN9c73cNIK63CglZCEavOLXxEvbPT3Opxv4UsmmQLB5BCqyEDSKw9'."\n".'FWZkYxeEY5wfJlmRkkvfK0OkAPbXYyI0xhY/UVtstutR5Tpzu3Plxq7xyOt/Pdl+'."\n".'3wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
