{*
* 2017 Areama
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Areama <contact@areama.net>
*  @copyright  2017 Areama
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Areama
*}

<style type="text/css">
    #arlg-config-tabs{
        opacity: 0;
        transition: 0.2s all;
    }
    #arlg-config-tabs.active{
        opacity: 1;
    }
    #arlg-config .form-group .form-group{
        margin-bottom: 0;
    }
    #arlg-config .form-group .form-group .color{
        margin-left: 5px;
    }
</style>
<div class="row" id="arlg-config">
    <div class="col-lg-2 col-md-3">
        <div class="list-group arlgTabs">
            <a class="list-group-item {if empty($active_tab) or $active_tab === 'ArLgGeneralConfigForm'}active{/if}" data-tab="0" id="arlg-tab-0" data-target="arlg-general" href="#">
                <i class="icon-cog"></i> {l s='General configuration' mod='arlg'}
            </a>
            <a class="list-group-item {if $active_tab === 'ArLgConfigForm'}active{/if}" data-tab="1" id="arlg-tab-1" data-target="arlg-gallery" href="#">
                <i class="icon-cog"></i> {l s='Gallery settings' mod='arlg'}
            </a>
            <a class="list-group-item {if $active_tab === 'ArLgSliderConfigForm' || $active_tab === 'ArLgSliderMobileConfigForm'}active{/if}" data-tab="2" id="arlg-tab-2" data-target="arlg-slider" href="#">
                <i class="icon-cog"></i> {l s='Slider settings' mod='arlg'}
            </a>
            <a class="list-group-item {if $active_tab === 'ArLgMagnifyConfigForm'}active{/if}" data-tab="3" id="arlg-tab-3" data-target="arlg-magnify" href="#">
                <i class="icon-cog"></i> {l s='Magnifier settings' mod='arlg'}
            </a>
            <a class="list-group-item" data-tab="4" id="arlg-tab-4" data-target="arlg-about" href="#">
                <i class="icon-info"></i> {l s='About' mod='arlg'}
            </a>
        </div>
    </div>
    <div class="col-lg-10 col-md-9" id="arlg-config-tabs">
        {include file="./_partials/_general.tpl"}
        {include file="./_partials/_gallery.tpl"}
        {include file="./_partials/_slider.tpl"}
        {include file="./_partials/_magnify.tpl"}
        {include file="./_partials/_about.tpl"}
    </div>
</div>

<script type="text/javascript">
    var arAiReminderAjaxUrl = '{$ajaxUrl nofilter}'{* URL generated by Link object, no escape necessary. Escaping will break functionality *};
    window.addEventListener('load', function(){
        $(".arlgTabs a").click(function(e){
            e.preventDefault();
            $(".arlgTabs .active").removeClass('active');
            $(this).addClass('active');
            $('#arlg-config .arlg-config-panel').addClass('hidden');
            $('#' + $(this).data('target')).removeClass('hidden');
            $('#arlgActiveTab').remove();
            $('#arlgActiveTab').val($(this).data('tab'));
        });
        //$('.arlgTabs .active').trigger('click');
        arlgLoadModules();
        arlgSwitchFields();
        arlgSwitchMagnifierType();
        arlgSwitchSliderLayout();
        arlgSwitchSliderMobileLayout();
        arlgSwitchThumbnails();
        $('#ARLGS_MODE').change(function(){
            arlgSwitchSliderLayout();
        });
        $('#ARLGSM_MODE').change(function(){
            arlgSwitchSliderMobileLayout();
        });
        $('#ARLGM_TYPE').change(function(){
            arlgSwitchMagnifierType();
        });
        $('.prestashop-switch').click(function(){
            arlgSwitchFields();
        });
        $('#ARLGS_GALLERY, #ARLGSM_GALLERY').change(function(){
            arlgSwitchThumbnails();
        });
        $('#arlg-config-tabs').addClass('active');
    });
    
    function arlgSwitchSliderLayout(){
        if ($('#ARLGS_MODE').val() == 'vertical') {
            $('#arlg-slider-desktop .field_vertical_height, #arlg-slider-desktop .field_thumb_width, #arlg-slider-desktop .field_layout').removeClass('hidden');
            $('#arlg-slider-desktop .field_thumb_controls').addClass('hidden');
        } else {
            $('#arlg-slider-desktop .field_vertical_height, #arlg-slider-desktop .field_thumb_width, #arlg-slider-desktop .field_layout').addClass('hidden');
            $('#arlg-slider-desktop .field_thumb_controls').removeClass('hidden');
        }
    }
    
    function arlgSwitchSliderMobileLayout(){
        if ($('#ARLGSM_MODE').val() == 'vertical') {
            $('#arlg-slider-mobile .field_vertical_height, #arlg-slider-mobile .field_thumb_width, #arlg-slider-mobile .field_layout').removeClass('hidden');
            $('#arlg-slider-mobile .field_thumb_controls').addClass('hidden');
        } else {
            $('#arlg-slider-mobile .field_vertical_height, #arlg-slider-mobile .field_thumb_width, #arlg-slider-mobile .field_layout').addClass('hidden');
            $('#arlg-slider-mobile .field_thumb_controls').removeClass('hidden');
        }
    }
    
    function arlgSwitchMagnifierType(){
        if ($('#ARLGM_TYPE').val() == 'lens') {
            $('#arlg-magnify .field_width, #arlg-magnify .field_height, #arlg-magnify .field_fader, #arlg-magnify .field_fader_opacity').removeClass('hidden');
        } else {
            $('#arlg-magnify .field_width, #arlg-magnify .field_height, #arlg-magnify .field_fader, #arlg-magnify .field_fader_opacity').addClass('hidden');
        }
    }
    
    function arlgSwitchThumbnails(){
        if ($('#ARLGS_GALLERY').val() == 0 || $('#ARLGS_GALLERY').val() == 2) {
            if ($('#ARLGS_GALLERY').val() == 2){
                $('#arlg-slider-desktop .field_thumb_items_per_row').removeClass('hidden');
            } else {
                $('#arlg-slider-desktop .field_thumb_items_per_row').addClass('hidden');
            }
            $('#arlg-slider-desktop .field_thumb_controls, #arlg-slider-desktop .field_thumb_controls_offset').addClass('hidden');
        } else {
            $('#arlg-slider-desktop .field_thumb_items_per_row').addClass('hidden');
            $('#arlg-slider-desktop .field_thumb_controls, #arlg-slider-desktop .field_thumb_controls_offset').removeClass('hidden');
        }
        if ($('#ARLGSM_GALLERY').val() == 0 || $('#ARLGSM_GALLERY').val() == 2) {
            if ($('#ARLGSM_GALLERY').val() == 2){
                $('#arlg-slider-mobile .field_thumb_items_per_row').removeClass('hidden');
            } else {
                $('#arlg-slider-mobile .field_thumb_items_per_row').addClass('hidden');
            }
            $('#arlg-slider-mobile .field_thumb_controls, #arlg-slider-mobile .field_thumb_controls_offset').addClass('hidden');
        } else {
            $('#arlg-slider-mobile .field_thumb_items_per_row').addClass('hidden');
            $('#arlg-slider-mobile .field_thumb_controls, #arlg-slider-mobile .field_thumb_controls_offset').removeClass('hidden');
        }
    }
    
    function arlgSwitchFields(){
        
    }
    
    function arlgLoadModules(){
        $.post(
            arAiReminderAjaxUrl, {
                action: 'loadModules',
                ajax: true
            }, function(data){
                $('#areama-modules').html(data.content);
            }, 'json'
        );
    }
</script>