<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\CarrierConfigurationUpdater' shared autowired service.

$a = ($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php'));

return $this->privates['InPost\\Shipping\\CarrierConfigurationUpdater'] = new \InPost\Shipping\CarrierConfigurationUpdater($a, ($this->services['inpost.shipping.configuration.carriers'] ?? ($this->services['inpost.shipping.configuration.carriers'] = new \InPost\Shipping\Configuration\CarriersConfiguration())), ($this->privates['InPost\\Shipping\\ChoiceProvider\\ShippingServiceChoiceProvider'] ?? $this->load('getShippingServiceChoiceProviderService.php')), new \InPost\Shipping\Validator\ShipmentDimensionsValidator($a));
