<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.validator.geo_widget_configuration' shared autowired service.

return $this->services['inpost.shipping.validator.geo_widget_configuration'] = new \InPost\Shipping\Validator\GeoWidgetConfigurationValidator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())));
