<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.presenter.point_address' shared service.

return $this->services['inpost.shipping.presenter.point_address'] = new \InPost\Shipping\Presenter\PointAddressPresenter(($this->services['inpost.shipping.presenter.point'] ?? $this->load('getInpost_Shipping_Presenter_PointService.php')));
