<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.geo_widget.token_provider' shared service.

return $this->services['inpost.shipping.geo_widget.token_provider'] = new \InPost\Shipping\GeoWidget\GeoWidgetTokenProvider(($this->services['inpost.shipping.configuration.geo_widget'] ?? ($this->services['inpost.shipping.configuration.geo_widget'] = new \InPost\Shipping\Configuration\GeoWidgetConfiguration())), ($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')));
