<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.dispatch_order.create' shared autowired service.

return $this->services['inpost.shipping.handler.dispatch_order.create'] = new \InPost\Shipping\Handler\DispatchOrder\CreateDispatchOrderHandler(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.translations.validation_errors'] ?? $this->load('getInpost_Shipping_Translations_ValidationErrorsService.php')), new \InPost\Shipping\Builder\DispatchOrder\CreateDispatchOrderPayloadBuilder());
