<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.translations.dimension_template' shared autowired service.

return $this->services['inpost.shipping.translations.dimension_template'] = new \InPost\Shipping\Translations\DimensionTemplateTranslator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
