<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.data_provider.order_shipments' shared autowired service.

return $this->services['inpost.shipping.data_provider.order_shipments'] = new \InPost\Shipping\DataProvider\OrderShipmentsDataProvider(($this->services['inpost.shipping.configuration.shipx'] ?? ($this->services['inpost.shipping.configuration.shipx'] = new \InPost\Shipping\Configuration\ShipXConfiguration())), ($this->services['InPost\\Shipping\\Presenter\\ShipmentPresenter'] ?? $this->load('getShipmentPresenterService.php')));
