<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\ShipX\ShipXClient' shared service.

return $this->privates['InPost\\Shipping\\ShipX\\ShipXClient'] = (new \InPost\Shipping\ShipX\ShipXClientFactory(new \InPost\Shipping\Api\PsrHttpImplementationFinder(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Psr\\Http\\Client\\ClientInterface' => ['privates', 'psr18.http_client', 'getPsr18_HttpClientService.php', true],
    'Psr\\Http\\Message\\StreamFactoryInterface' => ['privates', 'nyholm.psr7.psr17_factory', 'getNyholm_Psr7_Psr17FactoryService.php', true],
], [
    'Psr\\Http\\Client\\ClientInterface' => '?',
    'Psr\\Http\\Message\\StreamFactoryInterface' => '?',
]))))->createClient();
