<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'InPost\Shipping\Presenter\ShipmentPresenter' shared autowired service.

$a = ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php'));

return $this->services['InPost\\Shipping\\Presenter\\ShipmentPresenter'] = new \InPost\Shipping\Presenter\ShipmentPresenter(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), $a, ($this->services['inpost.shipping.translations.shipping_service'] ?? $this->load('getInpost_Shipping_Translations_ShippingServiceService.php')), ($this->services['inpost.shipping.translations.sending_method'] ?? $this->load('getInpost_Shipping_Translations_SendingMethodService.php')), ($this->services['inpost.shipping.translations.dimension_template'] ?? $this->load('getInpost_Shipping_Translations_DimensionTemplateService.php')), new \InPost\Shipping\Presenter\ShipmentStatusPresenter($a), ($this->services['inpost.shipping.configuration.szybkie_zwroty'] ?? ($this->services['inpost.shipping.configuration.szybkie_zwroty'] = new \InPost\Shipping\Configuration\SzybkieZwrotyConfiguration())), ($this->services['inpost.shipping.shop_context'] ?? ($this->services['inpost.shipping.shop_context'] = new \InPost\Shipping\PrestaShopContext())));
