<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.translations.shipping_service' shared autowired service.

return $this->services['inpost.shipping.translations.shipping_service'] = new \InPost\Shipping\Translations\ShippingServiceTranslator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
