<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.shipment.print_label' shared autowired service.

return $this->services['inpost.shipping.handler.shipment.print_label'] = new \InPost\Shipping\Handler\Shipment\PrintShipmentLabelHandler(($this->services['inpost.shipping.configuration.orders'] ?? ($this->services['inpost.shipping.configuration.orders'] = new \InPost\Shipping\Configuration\OrdersConfiguration())));
