<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.presenter.carrier' shared autowired service.

return $this->services['inpost.shipping.presenter.carrier'] = new \InPost\Shipping\Presenter\CarrierPresenter(($this->services['inpost.shipping.configuration.carriers'] ?? ($this->services['inpost.shipping.configuration.carriers'] = new \InPost\Shipping\Configuration\CarriersConfiguration())), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')));
