<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'TrustedshopsAddon\Service\OrderProductService' shared service.

return $this->services['TrustedshopsAddon\\Service\\OrderProductService'] = new \TrustedshopsAddon\Service\OrderProductService(($this->services['TrustedshopsAddon\\Repository\\OrderProductRepository'] ?? ($this->services['TrustedshopsAddon\\Repository\\OrderProductRepository'] = new \TrustedshopsAddon\Repository\OrderProductRepository())));
