<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'smartargetsocialfollowbar.ps_accounts_facade' shared service.

return $this->services['smartargetsocialfollowbar.ps_accounts_facade'] = new \PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts(($this->services['smartargetsocialfollowbar.ps_accounts_installer'] ?? ($this->services['smartargetsocialfollowbar.ps_accounts_installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('5.0'))));
