<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\ChoiceProvider\SendingMethodChoiceProvider' shared autowired service.

return $this->privates['InPost\\Shipping\\ChoiceProvider\\SendingMethodChoiceProvider'] = new \InPost\Shipping\ChoiceProvider\SendingMethodChoiceProvider(($this->services['inpost.shipping.translations.sending_method'] ?? $this->load('getInpost_Shipping_Translations_SendingMethodService.php')));
