<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'InPost\Shipping\Install\Database' shared autowired service.

return $this->services['InPost\\Shipping\\Install\\Database'] = new \InPost\Shipping\Install\Database(($this->services['inpost.shipping.configuration.shop'] ?? ($this->services['inpost.shipping.configuration.shop'] = new \InPost\Shipping\Configuration\ShopConfiguration())));
