<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.validator.sender' shared autowired service.

$a = ($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php'));
$b = ($this->privates['inpost.shipping.translations.validation_errors'] ?? $this->load('getInpost_Shipping_Translations_ValidationErrorsService.php'));

return $this->services['inpost.shipping.validator.sender'] = new \InPost\Shipping\Validator\SenderValidator($a, $b, new \InPost\Shipping\Validator\AddressValidator($a, $b));
