<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.views.modal.dispatch_order' shared autowired service.

return $this->services['inpost.shipping.views.modal.dispatch_order'] = new \InPost\Shipping\Views\Modal\CreateDispatchOrderModal(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\DispatchPointChoiceProvider'] ?? $this->load('getDispatchPointChoiceProviderService.php')), ($this->services['inpost.shipping.configuration.sending'] ?? ($this->services['inpost.shipping.configuration.sending'] = new \InPost\Shipping\Configuration\SendingConfiguration())));
