<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.product_update' shared autowired service.

return $this->services['inpost.shipping.handler.product_update'] = new \InPost\Shipping\Handler\ProductUpdateHandler(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\ShippingServiceChoiceProvider'] ?? $this->load('getShippingServiceChoiceProviderService.php')));
