<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'inpost.shipping.translations.validation_errors' shared autowired service.

return $this->privates['inpost.shipping.translations.validation_errors'] = new \InPost\Shipping\Translations\ValidationErrorTranslator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')));
