<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'smartargetsocialfollowbar.module' shared service.

return $this->services['smartargetsocialfollowbar.module'] = \Module::getInstanceByName('smartargetsocialfollowbar');
