<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'InPost\Shipping\CarrierUpdater' shared autowired service.

return $this->privates['InPost\\Shipping\\CarrierUpdater'] = new \InPost\Shipping\CarrierUpdater(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), ($this->privates['inpost.shipping.data_provider.language'] ?? ($this->privates['inpost.shipping.data_provider.language'] = new \InPost\Shipping\DataProvider\LanguageDataProvider())));
