<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.cron_jobs' shared service.

return $this->services['inpost.shipping.handler.cron_jobs'] = new \InPost\Shipping\Handler\CronJobsHandler(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), ($this->services['inpost.shipping.handler.shipment.update_status'] ?? $this->load('getInpost_Shipping_Handler_Shipment_UpdateStatusService.php')));
