<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.handler.update_service' shared autowired service.

return $this->services['inpost.shipping.handler.update_service'] = new \InPost\Shipping\Handler\ShippingService\UpdateServiceHandler(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['InPost\\Shipping\\CarrierUpdater'] ?? $this->load('getCarrierUpdaterService.php')), ($this->privates['InPost\\Shipping\\CarrierConfigurationUpdater'] ?? $this->load('getCarrierConfigurationUpdaterService.php')));
