<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.presenter.dispatch_point' shared autowired service.

return $this->services['inpost.shipping.presenter.dispatch_point'] = new \InPost\Shipping\Presenter\DispatchPointPresenter();
