<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.validator.module_controllers' shared autowired service.

return $this->services['inpost.shipping.validator.module_controllers'] = new \InPost\Shipping\Validator\ModuleControllersValidator(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['InPost\\Shipping\\ChoiceProvider\\ModulePageChoiceProvider'] ?? ($this->privates['InPost\\Shipping\\ChoiceProvider\\ModulePageChoiceProvider'] = new \InPost\Shipping\ChoiceProvider\ModulePageChoiceProvider())));
