<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'inpost.shipping.hook_dispatcher' shared service.

return $this->services['inpost.shipping.hook_dispatcher'] = new \InPost\Shipping\HookDispatcher(($this->privates['inpost.shipping.module'] ?? $this->load('getInpost_Shipping_ModuleService.php')), ($this->privates['inpost.shipping.context'] ?? $this->load('getInpost_Shipping_ContextService.php')), ($this->services['inpost.shipping.shop_context'] ?? ($this->services['inpost.shipping.shop_context'] = new \InPost\Shipping\PrestaShopContext())));
